{% set name = "gmatelastoplasticfinitestrainsimo" %}
{% set version = "0.2.0" %}
{% set sha256 = "717a4f89c88038d2af187114fbd5aea58d72222caadc878293212f5ebb1b669a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
    - gmattensor
  run:
    - xtensor
    - gmattensor

test:
  commands:
    - test -d ${PREFIX}/include/GMatElastoPlasticFiniteStrainSimo  # [unix]
    - test -f ${PREFIX}/include/GMatElastoPlasticFiniteStrainSimo/Cartesian3d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatElastoPlasticFiniteStrainSimo/GMatElastoPlasticFiniteStrainSimoConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatElastoPlasticFiniteStrainSimo\Cartesian3d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatElastoPlasticFiniteStrainSimoConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Finite strain elasto-plastic model (C++ header-only library).
  description: Finite strain elasto-plastic model (C++ header-only library).
  doc_url: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo
  dev_url: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo

extra:
  recipe-maintainers:
    - tdegeus
